<?php

use App\Regency;
use Illuminate\Database\Seeder;

class RegencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $regencies = array(
            array('id' => '1', 'province_id' => '1', 'code' => '1101', 'name' => 'Kab. Aceh Selatan'),
            array('id' => '2', 'province_id' => '1', 'code' => '1102', 'name' => 'Kab. Aceh Tenggara'),
            array('id' => '3', 'province_id' => '1', 'code' => '1103', 'name' => 'Kab. Aceh Timur'),
            array('id' => '4', 'province_id' => '1', 'code' => '1104', 'name' => 'Kab. Aceh Tengah'),
            array('id' => '5', 'province_id' => '1', 'code' => '1105', 'name' => 'Kab. Aceh Barat'),
            array('id' => '6', 'province_id' => '1', 'code' => '1106', 'name' => 'Kab. Aceh Besar'),
            array('id' => '7', 'province_id' => '1', 'code' => '1107', 'name' => 'Kab. Pidie'),
            array('id' => '8', 'province_id' => '1', 'code' => '1108', 'name' => 'Kab. Aceh Utara'),
            array('id' => '9', 'province_id' => '1', 'code' => '1109', 'name' => 'Kab. Simeulue'),
            array('id' => '10', 'province_id' => '1', 'code' => '1110', 'name' => 'Kab. Aceh Singkil'),
            array('id' => '11', 'province_id' => '1', 'code' => '1111', 'name' => 'Kab. Bireuen'),
            array('id' => '12', 'province_id' => '1', 'code' => '1112', 'name' => 'Kab. Aceh Barat Daya'),
            array('id' => '13', 'province_id' => '1', 'code' => '1113', 'name' => 'Kab. Gayo Lues'),
            array('id' => '14', 'province_id' => '1', 'code' => '1114', 'name' => 'Kab. Aceh Jaya'),
            array('id' => '15', 'province_id' => '1', 'code' => '1115', 'name' => 'Kab. Nagan Raya'),
            array('id' => '16', 'province_id' => '1', 'code' => '1116', 'name' => 'Kab. Aceh Tamiang'),
            array('id' => '17', 'province_id' => '1', 'code' => '1117', 'name' => 'Kab. Bener Meriah'),
            array('id' => '18', 'province_id' => '1', 'code' => '1118', 'name' => 'Kab. Pidie Jaya'),
            array('id' => '19', 'province_id' => '1', 'code' => '1171', 'name' => 'Kota Banda Aceh'),
            array('id' => '20', 'province_id' => '1', 'code' => '1172', 'name' => 'Kota Sabang'),
            array('id' => '21', 'province_id' => '1', 'code' => '1173', 'name' => 'Kota Lhokseumawe'),
            array('id' => '22', 'province_id' => '1', 'code' => '1174', 'name' => 'Kota Langsa'),
            array('id' => '23', 'province_id' => '1', 'code' => '1175', 'name' => 'Kota Subulussalam'),
            array('id' => '24', 'province_id' => '2', 'code' => '1201', 'name' => 'Kab. Tapanuli Tengah'),
            array('id' => '25', 'province_id' => '2', 'code' => '1202', 'name' => 'Kab. Tapanuli Utara'),
            array('id' => '26', 'province_id' => '2', 'code' => '1203', 'name' => 'Kab. Tapanuli Selatan'),
            array('id' => '27', 'province_id' => '2', 'code' => '1204', 'name' => 'Kab. Nias'),
            array('id' => '28', 'province_id' => '2', 'code' => '1205', 'name' => 'Kab. Langkat'),
            array('id' => '29', 'province_id' => '2', 'code' => '1206', 'name' => 'Kab. Karo'),
            array('id' => '30', 'province_id' => '2', 'code' => '1207', 'name' => 'Kab. Deli Serdang'),
            array('id' => '31', 'province_id' => '2', 'code' => '1208', 'name' => 'Kab. Simalungun'),
            array('id' => '32', 'province_id' => '2', 'code' => '1209', 'name' => 'Kab. Asahan'),
            array('id' => '33', 'province_id' => '2', 'code' => '1210', 'name' => 'Kab. Labuhanbatu'),
            array('id' => '34', 'province_id' => '2', 'code' => '1211', 'name' => 'Kab. Dairi'),
            array('id' => '35', 'province_id' => '2', 'code' => '1212', 'name' => 'Kab. Toba Samosir'),
            array('id' => '36', 'province_id' => '2', 'code' => '1213', 'name' => 'Kab. Mandailing Natal'),
            array('id' => '37', 'province_id' => '2', 'code' => '1214', 'name' => 'Kab. Nias Selatan'),
            array('id' => '38', 'province_id' => '2', 'code' => '1215', 'name' => 'Kab. Pakpak Bharat'),
            array('id' => '39', 'province_id' => '2', 'code' => '1216', 'name' => 'Kab. Humbang Hasundutan'),
            array('id' => '40', 'province_id' => '2', 'code' => '1217', 'name' => 'Kab. Samosir'),
            array('id' => '41', 'province_id' => '2', 'code' => '1218', 'name' => 'Kab. Serdang Bedagai'),
            array('id' => '42', 'province_id' => '2', 'code' => '1219', 'name' => 'Kab. Batu Bara'),
            array('id' => '43', 'province_id' => '2', 'code' => '1220', 'name' => 'Kab. Padang Lawas Utara'),
            array('id' => '44', 'province_id' => '2', 'code' => '1221', 'name' => 'Kab. Padang Lawas'),
            array('id' => '45', 'province_id' => '2', 'code' => '1222', 'name' => 'Kab. Labuhanbatu Selatan'),
            array('id' => '46', 'province_id' => '2', 'code' => '1223', 'name' => 'Kab. Labuhanbatu Utara'),
            array('id' => '47', 'province_id' => '2', 'code' => '1224', 'name' => 'Kab. Nias Utara'),
            array('id' => '48', 'province_id' => '2', 'code' => '1225', 'name' => 'Kab. Nias Barat'),
            array('id' => '49', 'province_id' => '2', 'code' => '1271', 'name' => 'Kota Medan'),
            array('id' => '50', 'province_id' => '2', 'code' => '1272', 'name' => 'Kota Pematangsiantar'),
            array('id' => '51', 'province_id' => '2', 'code' => '1273', 'name' => 'Kota Sibolga'),
            array('id' => '52', 'province_id' => '2', 'code' => '1274', 'name' => 'Kota Tanjung Balai'),
            array('id' => '53', 'province_id' => '2', 'code' => '1275', 'name' => 'Kota Binjai'),
            array('id' => '54', 'province_id' => '2', 'code' => '1276', 'name' => 'Kota Tebing Tinggi'),
            array('id' => '55', 'province_id' => '2', 'code' => '1277', 'name' => 'Kota Padangsidimpuan'),
            array('id' => '56', 'province_id' => '2', 'code' => '1278', 'name' => 'Kota Gunungsitoli'),
            array('id' => '57', 'province_id' => '3', 'code' => '1301', 'name' => 'Kab. Pesisir Selatan'),
            array('id' => '58', 'province_id' => '3', 'code' => '1302', 'name' => 'Kab. Solok'),
            array('id' => '59', 'province_id' => '3', 'code' => '1303', 'name' => 'Kab. Sijunjung'),
            array('id' => '60', 'province_id' => '3', 'code' => '1304', 'name' => 'Kab. Tanah Datar'),
            array('id' => '61', 'province_id' => '3', 'code' => '1305', 'name' => 'Kab. Padang Pariaman'),
            array('id' => '62', 'province_id' => '3', 'code' => '1306', 'name' => 'Kab. Agam'),
            array('id' => '63', 'province_id' => '3', 'code' => '1307', 'name' => 'Kab. Lima Puluh Kota'),
            array('id' => '64', 'province_id' => '3', 'code' => '1308', 'name' => 'Kab. Pasaman'),
            array('id' => '65', 'province_id' => '3', 'code' => '1309', 'name' => 'Kab. Kepulauan Mentawai'),
            array('id' => '66', 'province_id' => '3', 'code' => '1310', 'name' => 'Kab. Dharmasraya'),
            array('id' => '67', 'province_id' => '3', 'code' => '1311', 'name' => 'Kab. Solok Selatan'),
            array('id' => '68', 'province_id' => '3', 'code' => '1312', 'name' => 'Kab. Pasaman Barat'),
            array('id' => '69', 'province_id' => '3', 'code' => '1371', 'name' => 'Kota Padang'),
            array('id' => '70', 'province_id' => '3', 'code' => '1372', 'name' => 'Kota Solok'),
            array('id' => '71', 'province_id' => '3', 'code' => '1373', 'name' => 'Kota Sawahlunto'),
            array('id' => '72', 'province_id' => '3', 'code' => '1374', 'name' => 'Kota Padang Panjang'),
            array('id' => '73', 'province_id' => '3', 'code' => '1375', 'name' => 'Kota Bukittinggi'),
            array('id' => '74', 'province_id' => '3', 'code' => '1376', 'name' => 'Kota Payakumbuh'),
            array('id' => '75', 'province_id' => '3', 'code' => '1377', 'name' => 'Kota Pariaman'),
            array('id' => '76', 'province_id' => '4', 'code' => '1401', 'name' => 'Kab. Kampar'),
            array('id' => '77', 'province_id' => '4', 'code' => '1402', 'name' => 'Kab. Indragiri Hulu'),
            array('id' => '78', 'province_id' => '4', 'code' => '1403', 'name' => 'Kab. Bengkalis'),
            array('id' => '79', 'province_id' => '4', 'code' => '1404', 'name' => 'Kab. Indragiri Hilir'),
            array('id' => '80', 'province_id' => '4', 'code' => '1405', 'name' => 'Kab. Pelalawan'),
            array('id' => '81', 'province_id' => '4', 'code' => '1406', 'name' => 'Kab. Rokan Hulu'),
            array('id' => '82', 'province_id' => '4', 'code' => '1407', 'name' => 'Kab. Rokan Hilir'),
            array('id' => '83', 'province_id' => '4', 'code' => '1408', 'name' => 'Kab. Siak'),
            array('id' => '84', 'province_id' => '4', 'code' => '1409', 'name' => 'Kab. Kuantan Singingi'),
            array('id' => '85', 'province_id' => '4', 'code' => '1410', 'name' => 'Kab. Kepulauan Meranti'),
            array('id' => '86', 'province_id' => '4', 'code' => '1471', 'name' => 'Kota Pekanbaru'),
            array('id' => '87', 'province_id' => '4', 'code' => '1472', 'name' => 'Kota Dumai'),
            array('id' => '88', 'province_id' => '5', 'code' => '1501', 'name' => 'Kab. Kerinci'),
            array('id' => '89', 'province_id' => '5', 'code' => '1502', 'name' => 'Kab. Merangin'),
            array('id' => '90', 'province_id' => '5', 'code' => '1503', 'name' => 'Kab. Sarolangun'),
            array('id' => '91', 'province_id' => '5', 'code' => '1504', 'name' => 'Kab. Batanghari'),
            array('id' => '92', 'province_id' => '5', 'code' => '1505', 'name' => 'Kab. Muaro Jambi'),
            array('id' => '93', 'province_id' => '5', 'code' => '1506', 'name' => 'Kab. Tanjung Jabung Barat'),
            array('id' => '94', 'province_id' => '5', 'code' => '1507', 'name' => 'Kab. Tanjung Jabung Timur'),
            array('id' => '95', 'province_id' => '5', 'code' => '1508', 'name' => 'Kab. Bungo'),
            array('id' => '96', 'province_id' => '5', 'code' => '1509', 'name' => 'Kab. Tebo'),
            array('id' => '97', 'province_id' => '5', 'code' => '1571', 'name' => 'Kota Jambi'),
            array('id' => '98', 'province_id' => '5', 'code' => '1572', 'name' => 'Kota Sungai Penuh'),
            array('id' => '99', 'province_id' => '6', 'code' => '1601', 'name' => 'Kab. Ogan Komering Ulu'),
            array('id' => '100', 'province_id' => '6', 'code' => '1602', 'name' => 'Kab. Ogan Komering Ilir'),
            array('id' => '101', 'province_id' => '6', 'code' => '1603', 'name' => 'Kab. Muara Enim'),
            array('id' => '102', 'province_id' => '6', 'code' => '1604', 'name' => 'Kab. Lahat'),
            array('id' => '103', 'province_id' => '6', 'code' => '1605', 'name' => 'Kab. Musi Rawas'),
            array('id' => '104', 'province_id' => '6', 'code' => '1606', 'name' => 'Kab. Musi Banyuasin'),
            array('id' => '105', 'province_id' => '6', 'code' => '1607', 'name' => 'Kab. Banyuasin'),
            array('id' => '106', 'province_id' => '6', 'code' => '1608', 'name' => 'Kab. Ogan Komering Ulu Timur'),
            array('id' => '107', 'province_id' => '6', 'code' => '1609', 'name' => 'Kab. Ogan Komering Ulu Selatan'),
            array('id' => '108', 'province_id' => '6', 'code' => '1610', 'name' => 'Kab. Ogan Ilir'),
            array('id' => '109', 'province_id' => '6', 'code' => '1611', 'name' => 'Kab. Empat Lawang'),
            array('id' => '110', 'province_id' => '6', 'code' => '1612', 'name' => 'Kab. Penukal Abab Lematang Ilir'),
            array('id' => '111', 'province_id' => '6', 'code' => '1613', 'name' => 'Kab. Musi Rawas Utara'),
            array('id' => '112', 'province_id' => '6', 'code' => '1671', 'name' => 'Kota Palembang'),
            array('id' => '113', 'province_id' => '6', 'code' => '1672', 'name' => 'Kota Pagar Alam'),
            array('id' => '114', 'province_id' => '6', 'code' => '1673', 'name' => 'Kota Lubuk Linggau'),
            array('id' => '115', 'province_id' => '6', 'code' => '1674', 'name' => 'Kota Prabumulih'),
            array('id' => '116', 'province_id' => '7', 'code' => '1701', 'name' => 'Kab. Bengkulu Selatan'),
            array('id' => '117', 'province_id' => '7', 'code' => '1702', 'name' => 'Kab. Rejang Lebong'),
            array('id' => '118', 'province_id' => '7', 'code' => '1703', 'name' => 'Kab. Bengkulu Utara'),
            array('id' => '119', 'province_id' => '7', 'code' => '1704', 'name' => 'Kab. Kaur'),
            array('id' => '120', 'province_id' => '7', 'code' => '1705', 'name' => 'Kab. Seluma'),
            array('id' => '121', 'province_id' => '7', 'code' => '1706', 'name' => 'Kab. Muko Muko'),
            array('id' => '122', 'province_id' => '7', 'code' => '1707', 'name' => 'Kab. Lebong'),
            array('id' => '123', 'province_id' => '7', 'code' => '1708', 'name' => 'Kab. Kepahiang'),
            array('id' => '124', 'province_id' => '7', 'code' => '1709', 'name' => 'Kab. Bengkulu Tengah'),
            array('id' => '125', 'province_id' => '7', 'code' => '1771', 'name' => 'Kota Bengkulu'),
            array('id' => '126', 'province_id' => '8', 'code' => '1801', 'name' => 'Kab. Lampung Selatan'),
            array('id' => '127', 'province_id' => '8', 'code' => '1802', 'name' => 'Kab. Lampung Tengah'),
            array('id' => '128', 'province_id' => '8', 'code' => '1803', 'name' => 'Kab. Lampung Utara'),
            array('id' => '129', 'province_id' => '8', 'code' => '1804', 'name' => 'Kab. Lampung Barat'),
            array('id' => '130', 'province_id' => '8', 'code' => '1805', 'name' => 'Kab. Tulang Bawang'),
            array('id' => '131', 'province_id' => '8', 'code' => '1806', 'name' => 'Kab. Tanggamus'),
            array('id' => '132', 'province_id' => '8', 'code' => '1807', 'name' => 'Kab. Lampung Timur'),
            array('id' => '133', 'province_id' => '8', 'code' => '1808', 'name' => 'Kab. Way Kanan'),
            array('id' => '134', 'province_id' => '8', 'code' => '1809', 'name' => 'Kab. Pesawaran'),
            array('id' => '135', 'province_id' => '8', 'code' => '1810', 'name' => 'Kab. Pringsewu'),
            array('id' => '136', 'province_id' => '8', 'code' => '1811', 'name' => 'Kab. Mesuji'),
            array('id' => '137', 'province_id' => '8', 'code' => '1812', 'name' => 'Kab. Tulang Bawang Barat'),
            array('id' => '138', 'province_id' => '8', 'code' => '1813', 'name' => 'Kab. Pesisir Barat'),
            array('id' => '139', 'province_id' => '8', 'code' => '1871', 'name' => 'Kota Bandar Lampung'),
            array('id' => '140', 'province_id' => '8', 'code' => '1872', 'name' => 'Kota Metro'),
            array('id' => '141', 'province_id' => '9', 'code' => '1901', 'name' => 'Kab. Bangka'),
            array('id' => '142', 'province_id' => '9', 'code' => '1902', 'name' => 'Kab. Belitung'),
            array('id' => '143', 'province_id' => '9', 'code' => '1903', 'name' => 'Kab. Bangka Selatan'),
            array('id' => '144', 'province_id' => '9', 'code' => '1904', 'name' => 'Kab. Bangka Tengah'),
            array('id' => '145', 'province_id' => '9', 'code' => '1905', 'name' => 'Kab. Bangka Barat'),
            array('id' => '146', 'province_id' => '9', 'code' => '1906', 'name' => 'Kab. Belitung Timur'),
            array('id' => '147', 'province_id' => '9', 'code' => '1971', 'name' => 'Kota Pangkal Pinang'),
            array('id' => '148', 'province_id' => '10', 'code' => '2101', 'name' => 'Kab. Bintan'),
            array('id' => '149', 'province_id' => '10', 'code' => '2102', 'name' => 'Kab. Karimun'),
            array('id' => '150', 'province_id' => '10', 'code' => '2103', 'name' => 'Kab. Natuna'),
            array('id' => '151', 'province_id' => '10', 'code' => '2104', 'name' => 'Kab. Lingga'),
            array('id' => '152', 'province_id' => '10', 'code' => '2105', 'name' => 'Kab. Kepulauan Anambas'),
            array('id' => '153', 'province_id' => '10', 'code' => '2171', 'name' => 'Kota Batam'),
            array('id' => '154', 'province_id' => '10', 'code' => '2172', 'name' => 'Kota Tanjung Pinang'),
            array('id' => '155', 'province_id' => '11', 'code' => '3101', 'name' => 'Kab. Adm. Kep. Seribu'),
            array('id' => '156', 'province_id' => '11', 'code' => '3171', 'name' => 'Kota Adm. Jakarta Pusat'),
            array('id' => '157', 'province_id' => '11', 'code' => '3172', 'name' => 'Kota Adm. Jakarta Utara'),
            array('id' => '158', 'province_id' => '11', 'code' => '3173', 'name' => 'Kota Adm. Jakarta Barat'),
            array('id' => '159', 'province_id' => '11', 'code' => '3174', 'name' => 'Kota Adm. Jakarta Selatan'),
            array('id' => '160', 'province_id' => '11', 'code' => '3175', 'name' => 'Kota Adm. Jakarta Timur'),
            array('id' => '161', 'province_id' => '12', 'code' => '3201', 'name' => 'Kab. Bogor'),
            array('id' => '162', 'province_id' => '12', 'code' => '3202', 'name' => 'Kab. Sukabumi'),
            array('id' => '163', 'province_id' => '12', 'code' => '3203', 'name' => 'Kab. Cianjur'),
            array('id' => '164', 'province_id' => '12', 'code' => '3204', 'name' => 'Kab. Bandung'),
            array('id' => '165', 'province_id' => '12', 'code' => '3205', 'name' => 'Kab. Garut'),
            array('id' => '166', 'province_id' => '12', 'code' => '3206', 'name' => 'Kab. Tasikmalaya'),
            array('id' => '167', 'province_id' => '12', 'code' => '3207', 'name' => 'Kab. Ciamis'),
            array('id' => '168', 'province_id' => '12', 'code' => '3208', 'name' => 'Kab. Kuningan'),
            array('id' => '169', 'province_id' => '12', 'code' => '3209', 'name' => 'Kab. Cirebon'),
            array('id' => '170', 'province_id' => '12', 'code' => '3210', 'name' => 'Kab. Majalengka'),
            array('id' => '171', 'province_id' => '12', 'code' => '3211', 'name' => 'Kab. Sumedang'),
            array('id' => '172', 'province_id' => '12', 'code' => '3212', 'name' => 'Kab. Indramayu'),
            array('id' => '173', 'province_id' => '12', 'code' => '3213', 'name' => 'Kab. Subang'),
            array('id' => '174', 'province_id' => '12', 'code' => '3214', 'name' => 'Kab. Purwakarta'),
            array('id' => '175', 'province_id' => '12', 'code' => '3215', 'name' => 'Kab. Karawang'),
            array('id' => '176', 'province_id' => '12', 'code' => '3216', 'name' => 'Kab. Bekasi'),
            array('id' => '177', 'province_id' => '12', 'code' => '3217', 'name' => 'Kab. Bandung Barat'),
            array('id' => '178', 'province_id' => '12', 'code' => '3218', 'name' => 'Kab. Pangandaran'),
            array('id' => '179', 'province_id' => '12', 'code' => '3271', 'name' => 'Kota Bogor'),
            array('id' => '180', 'province_id' => '12', 'code' => '3272', 'name' => 'Kota Sukabumi'),
            array('id' => '181', 'province_id' => '12', 'code' => '3273', 'name' => 'Kota Bandung'),
            array('id' => '182', 'province_id' => '12', 'code' => '3274', 'name' => 'Kota Cirebon'),
            array('id' => '183', 'province_id' => '12', 'code' => '3275', 'name' => 'Kota Bekasi'),
            array('id' => '184', 'province_id' => '12', 'code' => '3276', 'name' => 'Kota Depok'),
            array('id' => '185', 'province_id' => '12', 'code' => '3277', 'name' => 'Kota Cimahi'),
            array('id' => '186', 'province_id' => '12', 'code' => '3278', 'name' => 'Kota Tasikmalaya'),
            array('id' => '187', 'province_id' => '12', 'code' => '3279', 'name' => 'Kota Banjar'),
            array('id' => '188', 'province_id' => '13', 'code' => '3301', 'name' => 'Kab. Cilacap'),
            array('id' => '189', 'province_id' => '13', 'code' => '3302', 'name' => 'Kab. Banyumas'),
            array('id' => '190', 'province_id' => '13', 'code' => '3303', 'name' => 'Kab. Purbalingga'),
            array('id' => '191', 'province_id' => '13', 'code' => '3304', 'name' => 'Kab. Banjarnegara'),
            array('id' => '192', 'province_id' => '13', 'code' => '3305', 'name' => 'Kab. Kebumen'),
            array('id' => '193', 'province_id' => '13', 'code' => '3306', 'name' => 'Kab. Purworejo'),
            array('id' => '194', 'province_id' => '13', 'code' => '3307', 'name' => 'Kab. Wonosobo'),
            array('id' => '195', 'province_id' => '13', 'code' => '3308', 'name' => 'Kab. Magelang'),
            array('id' => '196', 'province_id' => '13', 'code' => '3309', 'name' => 'Kab. Boyolali'),
            array('id' => '197', 'province_id' => '13', 'code' => '3310', 'name' => 'Kab. Klaten'),
            array('id' => '198', 'province_id' => '13', 'code' => '3311', 'name' => 'Kab. Sukoharjo'),
            array('id' => '199', 'province_id' => '13', 'code' => '3312', 'name' => 'Kab. Wonogiri'),
            array('id' => '200', 'province_id' => '13', 'code' => '3313', 'name' => 'Kab. Karanganyar'),
            array('id' => '201', 'province_id' => '13', 'code' => '3314', 'name' => 'Kab. Sragen'),
            array('id' => '202', 'province_id' => '13', 'code' => '3315', 'name' => 'Kab. Grobogan'),
            array('id' => '203', 'province_id' => '13', 'code' => '3316', 'name' => 'Kab. Blora'),
            array('id' => '204', 'province_id' => '13', 'code' => '3317', 'name' => 'Kab. Rembang'),
            array('id' => '205', 'province_id' => '13', 'code' => '3318', 'name' => 'Kab. Pati'),
            array('id' => '206', 'province_id' => '13', 'code' => '3319', 'name' => 'Kab. Kudus'),
            array('id' => '207', 'province_id' => '13', 'code' => '3320', 'name' => 'Kab. Jepara'),
            array('id' => '208', 'province_id' => '13', 'code' => '3321', 'name' => 'Kab. Demak'),
            array('id' => '209', 'province_id' => '13', 'code' => '3322', 'name' => 'Kab. Semarang'),
            array('id' => '210', 'province_id' => '13', 'code' => '3323', 'name' => 'Kab. Temanggung'),
            array('id' => '211', 'province_id' => '13', 'code' => '3324', 'name' => 'Kab. Kendal'),
            array('id' => '212', 'province_id' => '13', 'code' => '3325', 'name' => 'Kab. Batang'),
            array('id' => '213', 'province_id' => '13', 'code' => '3326', 'name' => 'Kab. Pekalongan'),
            array('id' => '214', 'province_id' => '13', 'code' => '3327', 'name' => 'Kab. Pemalang'),
            array('id' => '215', 'province_id' => '13', 'code' => '3328', 'name' => 'Kab. Tegal'),
            array('id' => '216', 'province_id' => '13', 'code' => '3329', 'name' => 'Kab. Brebes'),
            array('id' => '217', 'province_id' => '13', 'code' => '3371', 'name' => 'Kota Magelang'),
            array('id' => '218', 'province_id' => '13', 'code' => '3372', 'name' => 'Kota Surakarta'),
            array('id' => '219', 'province_id' => '13', 'code' => '3373', 'name' => 'Kota Salatiga'),
            array('id' => '220', 'province_id' => '13', 'code' => '3374', 'name' => 'Kota Semarang'),
            array('id' => '221', 'province_id' => '13', 'code' => '3375', 'name' => 'Kota Pekalongan'),
            array('id' => '222', 'province_id' => '13', 'code' => '3376', 'name' => 'Kota Tegal'),
            array('id' => '223', 'province_id' => '14', 'code' => '3401', 'name' => 'Kab. Kulon Progo'),
            array('id' => '224', 'province_id' => '14', 'code' => '3402', 'name' => 'Kab. Bantul'),
            array('id' => '225', 'province_id' => '14', 'code' => '3403', 'name' => 'Kab. Gunungkidul'),
            array('id' => '226', 'province_id' => '14', 'code' => '3404', 'name' => 'Kab. Sleman'),
            array('id' => '227', 'province_id' => '14', 'code' => '3471', 'name' => 'Kota Yogyakarta'),
            array('id' => '228', 'province_id' => '15', 'code' => '3501', 'name' => 'Kab. Pacitan'),
            array('id' => '229', 'province_id' => '15', 'code' => '3502', 'name' => 'Kab. Ponorogo'),
            array('id' => '230', 'province_id' => '15', 'code' => '3503', 'name' => 'Kab. Trenggalek'),
            array('id' => '231', 'province_id' => '15', 'code' => '3504', 'name' => 'Kab. Tulungagung'),
            array('id' => '232', 'province_id' => '15', 'code' => '3505', 'name' => 'Kab. Blitar'),
            array('id' => '233', 'province_id' => '15', 'code' => '3506', 'name' => 'Kab. Kediri'),
            array('id' => '234', 'province_id' => '15', 'code' => '3507', 'name' => 'Kab. Malang'),
            array('id' => '235', 'province_id' => '15', 'code' => '3508', 'name' => 'Kab. Lumajang'),
            array('id' => '236', 'province_id' => '15', 'code' => '3509', 'name' => 'Kab. Jember'),
            array('id' => '237', 'province_id' => '15', 'code' => '3510', 'name' => 'Kab. Banyuwangi'),
            array('id' => '238', 'province_id' => '15', 'code' => '3511', 'name' => 'Kab. Bondowoso'),
            array('id' => '239', 'province_id' => '15', 'code' => '3512', 'name' => 'Kab. Situbondo'),
            array('id' => '240', 'province_id' => '15', 'code' => '3513', 'name' => 'Kab. Probolinggo'),
            array('id' => '241', 'province_id' => '15', 'code' => '3514', 'name' => 'Kab. Pasuruan'),
            array('id' => '242', 'province_id' => '15', 'code' => '3515', 'name' => 'Kab. Sidoarjo'),
            array('id' => '243', 'province_id' => '15', 'code' => '3516', 'name' => 'Kab. Mojokerto'),
            array('id' => '244', 'province_id' => '15', 'code' => '3517', 'name' => 'Kab. Jombang'),
            array('id' => '245', 'province_id' => '15', 'code' => '3518', 'name' => 'Kab. Nganjuk'),
            array('id' => '246', 'province_id' => '15', 'code' => '3519', 'name' => 'Kab. Madiun'),
            array('id' => '247', 'province_id' => '15', 'code' => '3520', 'name' => 'Kab. Magetan'),
            array('id' => '248', 'province_id' => '15', 'code' => '3521', 'name' => 'Kab. Ngawi'),
            array('id' => '249', 'province_id' => '15', 'code' => '3522', 'name' => 'Kab. Bojonegoro'),
            array('id' => '250', 'province_id' => '15', 'code' => '3523', 'name' => 'Kab. Tuban'),
            array('id' => '251', 'province_id' => '15', 'code' => '3524', 'name' => 'Kab. Lamongan'),
            array('id' => '252', 'province_id' => '15', 'code' => '3525', 'name' => 'Kab. Gresik'),
            array('id' => '253', 'province_id' => '15', 'code' => '3526', 'name' => 'Kab. Bangkalan'),
            array('id' => '254', 'province_id' => '15', 'code' => '3527', 'name' => 'Kab. Sampang'),
            array('id' => '255', 'province_id' => '15', 'code' => '3528', 'name' => 'Kab. Pamekasan'),
            array('id' => '256', 'province_id' => '15', 'code' => '3529', 'name' => 'Kab. Sumenep'),
            array('id' => '257', 'province_id' => '15', 'code' => '3571', 'name' => 'Kota Kediri'),
            array('id' => '258', 'province_id' => '15', 'code' => '3572', 'name' => 'Kota Blitar'),
            array('id' => '259', 'province_id' => '15', 'code' => '3573', 'name' => 'Kota Malang'),
            array('id' => '260', 'province_id' => '15', 'code' => '3574', 'name' => 'Kota Probolinggo'),
            array('id' => '261', 'province_id' => '15', 'code' => '3575', 'name' => 'Kota Pasuruan'),
            array('id' => '262', 'province_id' => '15', 'code' => '3576', 'name' => 'Kota Mojokerto'),
            array('id' => '263', 'province_id' => '15', 'code' => '3577', 'name' => 'Kota Madiun'),
            array('id' => '264', 'province_id' => '15', 'code' => '3578', 'name' => 'Kota Surabaya'),
            array('id' => '265', 'province_id' => '15', 'code' => '3579', 'name' => 'Kota Batu'),
            array('id' => '266', 'province_id' => '16', 'code' => '3601', 'name' => 'Kab. Pandeglang'),
            array('id' => '267', 'province_id' => '16', 'code' => '3602', 'name' => 'Kab. Lebak'),
            array('id' => '268', 'province_id' => '16', 'code' => '3603', 'name' => 'Kab. Tangerang'),
            array('id' => '269', 'province_id' => '16', 'code' => '3604', 'name' => 'Kab. Serang'),
            array('id' => '270', 'province_id' => '16', 'code' => '3671', 'name' => 'Kota Tangerang'),
            array('id' => '271', 'province_id' => '16', 'code' => '3672', 'name' => 'Kota Cilegon'),
            array('id' => '272', 'province_id' => '16', 'code' => '3673', 'name' => 'Kota Serang'),
            array('id' => '273', 'province_id' => '16', 'code' => '3674', 'name' => 'Kota Tangerang Selatan'),
            array('id' => '274', 'province_id' => '17', 'code' => '5101', 'name' => 'Kab. Jembrana'),
            array('id' => '275', 'province_id' => '17', 'code' => '5102', 'name' => 'Kab. Tabanan'),
            array('id' => '276', 'province_id' => '17', 'code' => '5103', 'name' => 'Kab. Badung'),
            array('id' => '277', 'province_id' => '17', 'code' => '5104', 'name' => 'Kab. Gianyar'),
            array('id' => '278', 'province_id' => '17', 'code' => '5105', 'name' => 'Kab. Klungkung'),
            array('id' => '279', 'province_id' => '17', 'code' => '5106', 'name' => 'Kab. Bangli'),
            array('id' => '280', 'province_id' => '17', 'code' => '5107', 'name' => 'Kab. Karangasem'),
            array('id' => '281', 'province_id' => '17', 'code' => '5108', 'name' => 'Kab. Buleleng'),
            array('id' => '282', 'province_id' => '17', 'code' => '5171', 'name' => 'Kota Denpasar'),
            array('id' => '283', 'province_id' => '18', 'code' => '5201', 'name' => 'Kab. Lombok Barat'),
            array('id' => '284', 'province_id' => '18', 'code' => '5202', 'name' => 'Kab. Lombok Tengah'),
            array('id' => '285', 'province_id' => '18', 'code' => '5203', 'name' => 'Kab. Lombok Timur'),
            array('id' => '286', 'province_id' => '18', 'code' => '5204', 'name' => 'Kab. Sumbawa'),
            array('id' => '287', 'province_id' => '18', 'code' => '5205', 'name' => 'Kab. Dompu'),
            array('id' => '288', 'province_id' => '18', 'code' => '5206', 'name' => 'Kab. Bima'),
            array('id' => '289', 'province_id' => '18', 'code' => '5207', 'name' => 'Kab. Sumbawa Barat'),
            array('id' => '290', 'province_id' => '18', 'code' => '5208', 'name' => 'Kab. Lombok Utara'),
            array('id' => '291', 'province_id' => '18', 'code' => '5271', 'name' => 'Kota Mataram'),
            array('id' => '292', 'province_id' => '18', 'code' => '5272', 'name' => 'Kota Bima'),
            array('id' => '293', 'province_id' => '19', 'code' => '5301', 'name' => 'Kab. Kupang'),
            array('id' => '294', 'province_id' => '19', 'code' => '5302', 'name' => 'Kab Timor Tengah Selatan'),
            array('id' => '295', 'province_id' => '19', 'code' => '5303', 'name' => 'Kab. Timor Tengah Utara'),
            array('id' => '296', 'province_id' => '19', 'code' => '5304', 'name' => 'Kab. Belu'),
            array('id' => '297', 'province_id' => '19', 'code' => '5305', 'name' => 'Kab. Alor'),
            array('id' => '298', 'province_id' => '19', 'code' => '5306', 'name' => 'Kab. Flores Timur'),
            array('id' => '299', 'province_id' => '19', 'code' => '5307', 'name' => 'Kab. Sikka'),
            array('id' => '300', 'province_id' => '19', 'code' => '5308', 'name' => 'Kab. Ende'),
            array('id' => '301', 'province_id' => '19', 'code' => '5309', 'name' => 'Kab. Ngada'),
            array('id' => '302', 'province_id' => '19', 'code' => '5310', 'name' => 'Kab. Manggarai'),
            array('id' => '303', 'province_id' => '19', 'code' => '5311', 'name' => 'Kab. Sumba Timur'),
            array('id' => '304', 'province_id' => '19', 'code' => '5312', 'name' => 'Kab. Sumba Barat'),
            array('id' => '305', 'province_id' => '19', 'code' => '5313', 'name' => 'Kab. Lembata'),
            array('id' => '306', 'province_id' => '19', 'code' => '5314', 'name' => 'Kab. Rote Ndao'),
            array('id' => '307', 'province_id' => '19', 'code' => '5315', 'name' => 'Kab. Manggarai Barat'),
            array('id' => '308', 'province_id' => '19', 'code' => '5316', 'name' => 'Kab. Nagekeo'),
            array('id' => '309', 'province_id' => '19', 'code' => '5317', 'name' => 'Kab. Sumba Tengah'),
            array('id' => '310', 'province_id' => '19', 'code' => '5318', 'name' => 'Kab. Sumba Barat Daya'),
            array('id' => '311', 'province_id' => '19', 'code' => '5319', 'name' => 'Kab. Manggarai Timur'),
            array('id' => '312', 'province_id' => '19', 'code' => '5320', 'name' => 'Kab. Sabu Raijua'),
            array('id' => '313', 'province_id' => '19', 'code' => '5321', 'name' => 'Kab. Malaka'),
            array('id' => '314', 'province_id' => '19', 'code' => '5371', 'name' => 'Kota Kupang'),
            array('id' => '315', 'province_id' => '20', 'code' => '6101', 'name' => 'Kab. Sambas'),
            array('id' => '316', 'province_id' => '20', 'code' => '6102', 'name' => 'Kab. Mempawah'),
            array('id' => '317', 'province_id' => '20', 'code' => '6103', 'name' => 'Kab. Sanggau'),
            array('id' => '318', 'province_id' => '20', 'code' => '6104', 'name' => 'Kab. Ketapang'),
            array('id' => '319', 'province_id' => '20', 'code' => '6105', 'name' => 'Kab. Sintang'),
            array('id' => '320', 'province_id' => '20', 'code' => '6106', 'name' => 'Kab. Kapuas Hulu'),
            array('id' => '321', 'province_id' => '20', 'code' => '6107', 'name' => 'Kab. Bengkayang'),
            array('id' => '322', 'province_id' => '20', 'code' => '6108', 'name' => 'Kab. Landak'),
            array('id' => '323', 'province_id' => '20', 'code' => '6109', 'name' => 'Kab. Sekadau'),
            array('id' => '324', 'province_id' => '20', 'code' => '6110', 'name' => 'Kab. Melawi'),
            array('id' => '325', 'province_id' => '20', 'code' => '6111', 'name' => 'Kab. Kayong Utara'),
            array('id' => '326', 'province_id' => '20', 'code' => '6112', 'name' => 'Kab. Kubu Raya'),
            array('id' => '327', 'province_id' => '20', 'code' => '6171', 'name' => 'Kota Pontianak'),
            array('id' => '328', 'province_id' => '20', 'code' => '6172', 'name' => 'Kota Singkawang'),
            array('id' => '329', 'province_id' => '21', 'code' => '6201', 'name' => 'Kab. Kotawaringin Barat'),
            array('id' => '330', 'province_id' => '21', 'code' => '6202', 'name' => 'Kab. Kotawaringin Timur'),
            array('id' => '331', 'province_id' => '21', 'code' => '6203', 'name' => 'Kab. Kapuas'),
            array('id' => '332', 'province_id' => '21', 'code' => '6204', 'name' => 'Kab. Barito Selatan'),
            array('id' => '333', 'province_id' => '21', 'code' => '6205', 'name' => 'Kab. Barito Utara'),
            array('id' => '334', 'province_id' => '21', 'code' => '6206', 'name' => 'Kab. Katingan'),
            array('id' => '335', 'province_id' => '21', 'code' => '6207', 'name' => 'Kab. Seruyan'),
            array('id' => '336', 'province_id' => '21', 'code' => '6208', 'name' => 'Kab. Sukamara'),
            array('id' => '337', 'province_id' => '21', 'code' => '6209', 'name' => 'Kab. Lamandau'),
            array('id' => '338', 'province_id' => '21', 'code' => '6210', 'name' => 'Kab. Gunung Mas'),
            array('id' => '339', 'province_id' => '21', 'code' => '6211', 'name' => 'Kab. Pulang Pisau'),
            array('id' => '340', 'province_id' => '21', 'code' => '6212', 'name' => 'Kab. Murung Raya'),
            array('id' => '341', 'province_id' => '21', 'code' => '6213', 'name' => 'Kab. Barito Timur'),
            array('id' => '342', 'province_id' => '21', 'code' => '6271', 'name' => 'Kota Palangkaraya'),
            array('id' => '343', 'province_id' => '22', 'code' => '6301', 'name' => 'Kab. Tanah Laut'),
            array('id' => '344', 'province_id' => '22', 'code' => '6302', 'name' => 'Kab. Kotabaru'),
            array('id' => '345', 'province_id' => '22', 'code' => '6303', 'name' => 'Kab. Banjar'),
            array('id' => '346', 'province_id' => '22', 'code' => '6304', 'name' => 'Kab. Barito Kuala'),
            array('id' => '347', 'province_id' => '22', 'code' => '6305', 'name' => 'Kab. Tapin'),
            array('id' => '348', 'province_id' => '22', 'code' => '6306', 'name' => 'Kab. Hulu Sungai Selatan'),
            array('id' => '349', 'province_id' => '22', 'code' => '6307', 'name' => 'Kab. Hulu Sungai Tengah'),
            array('id' => '350', 'province_id' => '22', 'code' => '6308', 'name' => 'Kab. Hulu Sungai Utara'),
            array('id' => '351', 'province_id' => '22', 'code' => '6309', 'name' => 'Kab. Tabalong'),
            array('id' => '352', 'province_id' => '22', 'code' => '6310', 'name' => 'Kab. Tanah Bumbu'),
            array('id' => '353', 'province_id' => '22', 'code' => '6311', 'name' => 'Kab. Balangan'),
            array('id' => '354', 'province_id' => '22', 'code' => '6371', 'name' => 'Kota Banjarmasin'),
            array('id' => '355', 'province_id' => '22', 'code' => '6372', 'name' => 'Kota Banjarbaru'),
            array('id' => '356', 'province_id' => '23', 'code' => '6401', 'name' => 'Kab. Paser'),
            array('id' => '357', 'province_id' => '23', 'code' => '6402', 'name' => 'Kab. Kutai Kartanegara'),
            array('id' => '358', 'province_id' => '23', 'code' => '6403', 'name' => 'Kab. Berau'),
            array('id' => '359', 'province_id' => '23', 'code' => '6407', 'name' => 'Kab. Kutai Barat'),
            array('id' => '360', 'province_id' => '23', 'code' => '6408', 'name' => 'Kab. Kutai Timur'),
            array('id' => '361', 'province_id' => '23', 'code' => '6409', 'name' => 'Kab. Penajam Paser Utara'),
            array('id' => '362', 'province_id' => '23', 'code' => '6411', 'name' => 'Kab. Mahakam Ulu'),
            array('id' => '363', 'province_id' => '23', 'code' => '6471', 'name' => 'Kota Balikpapan'),
            array('id' => '364', 'province_id' => '23', 'code' => '6472', 'name' => 'Kota Samarinda'),
            array('id' => '365', 'province_id' => '23', 'code' => '6474', 'name' => 'Kota Bontang'),
            array('id' => '366', 'province_id' => '24', 'code' => '6501', 'name' => 'Kab. Bulungan'),
            array('id' => '367', 'province_id' => '24', 'code' => '6502', 'name' => 'Kab. Malinau'),
            array('id' => '368', 'province_id' => '24', 'code' => '6503', 'name' => 'Kab. Nunukan'),
            array('id' => '369', 'province_id' => '24', 'code' => '6504', 'name' => 'Kab. Tana Tidung'),
            array('id' => '370', 'province_id' => '24', 'code' => '6571', 'name' => 'Kota Tarakan'),
            array('id' => '371', 'province_id' => '25', 'code' => '7101', 'name' => 'Kab. Bolaang Mongondow'),
            array('id' => '372', 'province_id' => '25', 'code' => '7102', 'name' => 'Kab. Minahasa'),
            array('id' => '373', 'province_id' => '25', 'code' => '7103', 'name' => 'Kab. Kepulauan Sangihe'),
            array('id' => '374', 'province_id' => '25', 'code' => '7104', 'name' => 'Kab. Kepulauan Talaud'),
            array('id' => '375', 'province_id' => '25', 'code' => '7105', 'name' => 'Kab. Minahasa Selatan'),
            array('id' => '376', 'province_id' => '25', 'code' => '7106', 'name' => 'Kab. Minahasa Utara'),
            array('id' => '377', 'province_id' => '25', 'code' => '7107', 'name' => 'Kab. Minahasa Tenggara'),
            array('id' => '378', 'province_id' => '25', 'code' => '7108', 'name' => 'Kab. Bolaang Mongondow Utara'),
            array('id' => '379', 'province_id' => '25', 'code' => '7109', 'name' => 'Kab. Kep. Siau Tagulandang Biaro'),
            array('id' => '380', 'province_id' => '25', 'code' => '7110', 'name' => 'Kab. Bolaang Mongondow Timur'),
            array('id' => '381', 'province_id' => '25', 'code' => '7111', 'name' => 'Kab. Bolaang Mongondow Selatan'),
            array('id' => '382', 'province_id' => '25', 'code' => '7171', 'name' => 'Kota Manado'),
            array('id' => '383', 'province_id' => '25', 'code' => '7172', 'name' => 'Kota Bitung'),
            array('id' => '384', 'province_id' => '25', 'code' => '7173', 'name' => 'Kota Tomohon'),
            array('id' => '385', 'province_id' => '25', 'code' => '7174', 'name' => 'Kota Kotamobagu'),
            array('id' => '386', 'province_id' => '26', 'code' => '7201', 'name' => 'Kab. Banggai'),
            array('id' => '387', 'province_id' => '26', 'code' => '7202', 'name' => 'Kab. Poso'),
            array('id' => '388', 'province_id' => '26', 'code' => '7203', 'name' => 'Kab. Donggala'),
            array('id' => '389', 'province_id' => '26', 'code' => '7204', 'name' => 'Kab. Toli Toli'),
            array('id' => '390', 'province_id' => '26', 'code' => '7205', 'name' => 'Kab. Buol'),
            array('id' => '391', 'province_id' => '26', 'code' => '7206', 'name' => 'Kab. Morowali'),
            array('id' => '392', 'province_id' => '26', 'code' => '7207', 'name' => 'Kab. Banggai Kepulauan'),
            array('id' => '393', 'province_id' => '26', 'code' => '7208', 'name' => 'Kab. Parigi Moutong'),
            array('id' => '394', 'province_id' => '26', 'code' => '7209', 'name' => 'Kab. Tojo Una Una'),
            array('id' => '395', 'province_id' => '26', 'code' => '7210', 'name' => 'Kab. Sigi'),
            array('id' => '396', 'province_id' => '26', 'code' => '7211', 'name' => 'Kab. Banggai Laut'),
            array('id' => '397', 'province_id' => '26', 'code' => '7212', 'name' => 'Kab. Morowali Utara'),
            array('id' => '398', 'province_id' => '26', 'code' => '7271', 'name' => 'Kota Palu'),
            array('id' => '399', 'province_id' => '27', 'code' => '7301', 'name' => 'Kab. Kepulauan Selayar'),
            array('id' => '400', 'province_id' => '27', 'code' => '7302', 'name' => 'Kab. Bulukumba'),
            array('id' => '401', 'province_id' => '27', 'code' => '7303', 'name' => 'Kab. Bantaeng'),
            array('id' => '402', 'province_id' => '27', 'code' => '7304', 'name' => 'Kab. Jeneponto'),
            array('id' => '403', 'province_id' => '27', 'code' => '7305', 'name' => 'Kab. Takalar'),
            array('id' => '404', 'province_id' => '27', 'code' => '7306', 'name' => 'Kab. Gowa'),
            array('id' => '405', 'province_id' => '27', 'code' => '7307', 'name' => 'Kab. Sinjai'),
            array('id' => '406', 'province_id' => '27', 'code' => '7308', 'name' => 'Kab. Bone'),
            array('id' => '407', 'province_id' => '27', 'code' => '7309', 'name' => 'Kab. Maros'),
            array('id' => '408', 'province_id' => '27', 'code' => '7310', 'name' => 'Kab. Pangkajene Kepulauan'),
            array('id' => '409', 'province_id' => '27', 'code' => '7311', 'name' => 'Kab. Barru'),
            array('id' => '410', 'province_id' => '27', 'code' => '7312', 'name' => 'Kab. Soppeng'),
            array('id' => '411', 'province_id' => '27', 'code' => '7313', 'name' => 'Kab. Wajo'),
            array('id' => '412', 'province_id' => '27', 'code' => '7314', 'name' => 'Kab. Sidenreng Rappang'),
            array('id' => '413', 'province_id' => '27', 'code' => '7315', 'name' => 'Kab. Pinrang'),
            array('id' => '414', 'province_id' => '27', 'code' => '7316', 'name' => 'Kab. Enrekang'),
            array('id' => '415', 'province_id' => '27', 'code' => '7317', 'name' => 'Kab. Luwu'),
            array('id' => '416', 'province_id' => '27', 'code' => '7318', 'name' => 'Kab. Tana Toraja'),
            array('id' => '417', 'province_id' => '27', 'code' => '7322', 'name' => 'Kab. Luwu Utara'),
            array('id' => '418', 'province_id' => '27', 'code' => '7324', 'name' => 'Kab. Luwu Timur'),
            array('id' => '419', 'province_id' => '27', 'code' => '7326', 'name' => 'Kab. Toraja Utara'),
            array('id' => '420', 'province_id' => '27', 'code' => '7371', 'name' => 'Kota Makassar'),
            array('id' => '421', 'province_id' => '27', 'code' => '7372', 'name' => 'Kota Pare Pare'),
            array('id' => '422', 'province_id' => '27', 'code' => '7373', 'name' => 'Kota Palopo'),
            array('id' => '423', 'province_id' => '28', 'code' => '7401', 'name' => 'Kab. Kolaka'),
            array('id' => '424', 'province_id' => '28', 'code' => '7402', 'name' => 'Kab. Konawe'),
            array('id' => '425', 'province_id' => '28', 'code' => '7403', 'name' => 'Kab. Muna'),
            array('id' => '426', 'province_id' => '28', 'code' => '7404', 'name' => 'Kab. Buton'),
            array('id' => '427', 'province_id' => '28', 'code' => '7405', 'name' => 'Kab. Konawe Selatan'),
            array('id' => '428', 'province_id' => '28', 'code' => '7406', 'name' => 'Kab. Bombana'),
            array('id' => '429', 'province_id' => '28', 'code' => '7407', 'name' => 'Kab. Wakatobi'),
            array('id' => '430', 'province_id' => '28', 'code' => '7408', 'name' => 'Kab. Kolaka Utara'),
            array('id' => '431', 'province_id' => '28', 'code' => '7409', 'name' => 'Kab. Konawe Utara'),
            array('id' => '432', 'province_id' => '28', 'code' => '7410', 'name' => 'Kab. Buton Utara'),
            array('id' => '433', 'province_id' => '28', 'code' => '7411', 'name' => 'Kab. Kolaka Timur'),
            array('id' => '434', 'province_id' => '28', 'code' => '7412', 'name' => 'Kab. Konawe Kepulauan'),
            array('id' => '435', 'province_id' => '28', 'code' => '7413', 'name' => 'Kab. Muna Barat'),
            array('id' => '436', 'province_id' => '28', 'code' => '7414', 'name' => 'Kab. Buton Tengah'),
            array('id' => '437', 'province_id' => '28', 'code' => '7415', 'name' => 'Kab. Buton Selatan'),
            array('id' => '438', 'province_id' => '28', 'code' => '7471', 'name' => 'Kota Kendari'),
            array('id' => '439', 'province_id' => '28', 'code' => '7472', 'name' => 'Kota Bau Bau'),
            array('id' => '440', 'province_id' => '29', 'code' => '7501', 'name' => 'Kab. Gorontalo'),
            array('id' => '441', 'province_id' => '29', 'code' => '7502', 'name' => 'Kab. Boalemo'),
            array('id' => '442', 'province_id' => '29', 'code' => '7503', 'name' => 'Kab. Bone Bolango'),
            array('id' => '443', 'province_id' => '29', 'code' => '7504', 'name' => 'Kab. Pahuwato'),
            array('id' => '444', 'province_id' => '29', 'code' => '7505', 'name' => 'Kab. Gorontalo Utara'),
            array('id' => '445', 'province_id' => '29', 'code' => '7571', 'name' => 'Kota Gorontalo'),
            array('id' => '446', 'province_id' => '30', 'code' => '7601', 'name' => 'Kab. Mamuju Utara'),
            array('id' => '447', 'province_id' => '30', 'code' => '7602', 'name' => 'Kab. Mamuju'),
            array('id' => '448', 'province_id' => '30', 'code' => '7603', 'name' => 'Kab. Mamasa'),
            array('id' => '449', 'province_id' => '30', 'code' => '7604', 'name' => 'Kab. Polewali Mandar'),
            array('id' => '450', 'province_id' => '30', 'code' => '7605', 'name' => 'Kab. Majene'),
            array('id' => '451', 'province_id' => '30', 'code' => '7606', 'name' => 'Kab. Mamuju Tengah'),
            array('id' => '452', 'province_id' => '31', 'code' => '8101', 'name' => 'Kab. Maluku Tengah'),
            array('id' => '453', 'province_id' => '31', 'code' => '8102', 'name' => 'Kab. Maluku Tenggara'),
            array('id' => '454', 'province_id' => '31', 'code' => '8103', 'name' => 'Kab. Maluku Tenggara Barat'),
            array('id' => '455', 'province_id' => '31', 'code' => '8104', 'name' => 'Kab. Buru'),
            array('id' => '456', 'province_id' => '31', 'code' => '8105', 'name' => 'Kab. Seram Bagian Timur'),
            array('id' => '457', 'province_id' => '31', 'code' => '8106', 'name' => 'Kab. Seram Bagian Barat'),
            array('id' => '458', 'province_id' => '31', 'code' => '8107', 'name' => 'Kab. Kepulauan Aru'),
            array('id' => '459', 'province_id' => '31', 'code' => '8108', 'name' => 'Kab. Maluku Barat Daya'),
            array('id' => '460', 'province_id' => '31', 'code' => '8109', 'name' => 'Kab. Buru Selatan'),
            array('id' => '461', 'province_id' => '31', 'code' => '8171', 'name' => 'Kota Ambon'),
            array('id' => '462', 'province_id' => '31', 'code' => '8172', 'name' => 'Kota Tual'),
            array('id' => '463', 'province_id' => '32', 'code' => '8201', 'name' => 'Kab. Halmahera Barat'),
            array('id' => '464', 'province_id' => '32', 'code' => '8202', 'name' => 'Kab. Halmahera Tengah'),
            array('id' => '465', 'province_id' => '32', 'code' => '8203', 'name' => 'Kab. Halmahera Utara'),
            array('id' => '466', 'province_id' => '32', 'code' => '8204', 'name' => 'Kab. Halmahera Selatan'),
            array('id' => '467', 'province_id' => '32', 'code' => '8205', 'name' => 'Kab. Kepulauan Sula'),
            array('id' => '468', 'province_id' => '32', 'code' => '8206', 'name' => 'Kab. Halmahera Timur'),
            array('id' => '469', 'province_id' => '32', 'code' => '8207', 'name' => 'Kab. Pulau Morotai'),
            array('id' => '470', 'province_id' => '32', 'code' => '8208', 'name' => 'Kab. Pulau Taliabu'),
            array('id' => '471', 'province_id' => '32', 'code' => '8271', 'name' => 'Kota Ternate'),
            array('id' => '472', 'province_id' => '32', 'code' => '8272', 'name' => 'Kota Tidore Kepulauan'),
            array('id' => '473', 'province_id' => '33', 'code' => '9101', 'name' => 'Kab. Merauke'),
            array('id' => '474', 'province_id' => '33', 'code' => '9102', 'name' => 'Kab. Jayawijaya'),
            array('id' => '475', 'province_id' => '33', 'code' => '9103', 'name' => 'Kab. Jayapura'),
            array('id' => '476', 'province_id' => '33', 'code' => '9104', 'name' => 'Kab. Nabire'),
            array('id' => '477', 'province_id' => '33', 'code' => '9105', 'name' => 'Kab. Kepulauan Yapen'),
            array('id' => '478', 'province_id' => '33', 'code' => '9106', 'name' => 'Kab. Biak Numfor'),
            array('id' => '479', 'province_id' => '33', 'code' => '9107', 'name' => 'Kab. Puncak Jaya'),
            array('id' => '480', 'province_id' => '33', 'code' => '9108', 'name' => 'Kab. Paniai'),
            array('id' => '481', 'province_id' => '33', 'code' => '9109', 'name' => 'Kab. Mimika'),
            array('id' => '482', 'province_id' => '33', 'code' => '9110', 'name' => 'Kab. Sarmi'),
            array('id' => '483', 'province_id' => '33', 'code' => '9111', 'name' => 'Kab. Keerom'),
            array('id' => '484', 'province_id' => '33', 'code' => '9112', 'name' => 'Kab. Pegunungan Bintang'),
            array('id' => '485', 'province_id' => '33', 'code' => '9113', 'name' => 'Kab. Yahukimo'),
            array('id' => '486', 'province_id' => '33', 'code' => '9114', 'name' => 'Kab. Tolikara'),
            array('id' => '487', 'province_id' => '33', 'code' => '9115', 'name' => 'Kab. Waropen'),
            array('id' => '488', 'province_id' => '33', 'code' => '9116', 'name' => 'Kab. Boven Digoel'),
            array('id' => '489', 'province_id' => '33', 'code' => '9117', 'name' => 'Kab. Mappi'),
            array('id' => '490', 'province_id' => '33', 'code' => '9118', 'name' => 'Kab. Asmat'),
            array('id' => '491', 'province_id' => '33', 'code' => '9119', 'name' => 'Kab. Supiori'),
            array('id' => '492', 'province_id' => '33', 'code' => '9120', 'name' => 'Kab. Mamberamo Raya'),
            array('id' => '493', 'province_id' => '33', 'code' => '9121', 'name' => 'Kab. Mamberamo Tengah'),
            array('id' => '494', 'province_id' => '33', 'code' => '9122', 'name' => 'Kab. Yalimo'),
            array('id' => '495', 'province_id' => '33', 'code' => '9123', 'name' => 'Kab. Lanny Jaya'),
            array('id' => '496', 'province_id' => '33', 'code' => '9124', 'name' => 'Kab. Nduga'),
            array('id' => '497', 'province_id' => '33', 'code' => '9125', 'name' => 'Kab. Puncak'),
            array('id' => '498', 'province_id' => '33', 'code' => '9126', 'name' => 'Kab. Dogiyai'),
            array('id' => '499', 'province_id' => '33', 'code' => '9127', 'name' => 'Kab. Intan Jaya'),
            array('id' => '500', 'province_id' => '33', 'code' => '9128', 'name' => 'Kab. Deiyai'),
            array('id' => '501', 'province_id' => '33', 'code' => '9171', 'name' => 'Kota Jayapura'),
            array('id' => '502', 'province_id' => '34', 'code' => '9201', 'name' => 'Kab. Sorong'),
            array('id' => '503', 'province_id' => '34', 'code' => '9202', 'name' => 'Kab. Manokwari'),
            array('id' => '504', 'province_id' => '34', 'code' => '9203', 'name' => 'Kab. Fak Fak'),
            array('id' => '505', 'province_id' => '34', 'code' => '9204', 'name' => 'Kab. Sorong Selatan'),
            array('id' => '506', 'province_id' => '34', 'code' => '9205', 'name' => 'Kab. Raja Ampat'),
            array('id' => '507', 'province_id' => '34', 'code' => '9206', 'name' => 'Kab. Teluk Bintuni'),
            array('id' => '508', 'province_id' => '34', 'code' => '9207', 'name' => 'Kab. Teluk Wondama'),
            array('id' => '509', 'province_id' => '34', 'code' => '9208', 'name' => 'Kab. Kaimana'),
            array('id' => '510', 'province_id' => '34', 'code' => '9209', 'name' => 'Kab. Tambrauw'),
            array('id' => '511', 'province_id' => '34', 'code' => '9210', 'name' => 'Kab. Maybrat'),
            array('id' => '512', 'province_id' => '34', 'code' => '9211', 'name' => 'Kab. Manokwari Selatan'),
            array('id' => '513', 'province_id' => '34', 'code' => '9212', 'name' => 'Kab. Pegunungan Arfak'),
            array('id' => '514', 'province_id' => '34', 'code' => '9271', 'name' => 'Kota Sorong')
        );

        if (is_array($regencies) && count($regencies)) {
            Regency::query()->insert($regencies);
        }
    }
}
